### ISSUE TITLE
`Scope`s with `Control.Lens.Plated` lead to infinite loop and space leak

### ISSUE THREAD

**Issue by ThreeFx** [ekmett/bound#64] opened 2017-06-14 00:41 UTC
Using Bound with Lens breaks `Control.Lens.Plated` as `traverse` and `rewrite` loop infinitely and leak memory. Removing the `Lam` alternative (and thereby also the `Scope` resolves the issue. Attached is a (somewhat) minimal working example, `profiterole` and heap profiling results.

I am using GHC version 8.0.2, all packages with exception of `bound-2` are part of stack `lts-8.17`. The program is compiled as `ghc test.hs`. Enabling or disabling optimizations doesn't affect the problem.

(Potentially) see [this](https://stackoverflow.com/questions/44532493/space-leak-bug-in-interaction-of-control-lens-plated-and-bound) SO question for more information/discussion.

This issue might be in the wrong project, feel free to ping me and I'll sumbit it to `lens` instead.

-----
```haskell
{-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable, DeriveDataTypeable #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell    #-}

module Main (main) where
import           Bound
import           Control.Lens hiding (List)
import           Control.Lens.Plated
import           Data.Deriving (deriveShow1, deriveEq1)
import           Data.Data
import           Data.Data.Lens (uniplate)

data Expr a   = Var   a
              | List  [Expr a]
              | Apply (Expr a) (Expr a)
              | Lam   (Scope () Expr a)
              | Nop
              deriving (Functor, Foldable, Traversable, Data)

main = do
         print ex
         print $ transform removeTest ex

ex :: Expr String
ex = List [ Apply (Var "test") $ List [Var "arg1", Var "arg2"]
          , Apply (Var "two") (Var "three")]

removeTest :: Expr String -> Expr String
removeTest = \expr -> case expr of
                        Apply (Var "test") _ -> Nop
                        _ -> expr

instance Data a => Plated (Expr a) where
  plate = uniplate

makeLenses  ''Expr
makeBound   ''Expr
deriveEq1   ''Expr
deriveShow1 ''Expr
deriving instance Show a => Show (Expr a)
deriving instance Eq   a => Eq   (Expr a)
```
Output:
```haskell
List [Apply (Var "test") (List [Var "arg1",Var "arg2"])
     ,Apply (Var "two") (Var "three")]
^CList [Nop,Apply (Var "two") (Var "three")]
```
----
```
 -- profiterole stats
 TOT   INH   IND
99.9  99.9    .1  MAIN MAIN (0)

99.9  99.9    .1  MAIN MAIN (0)
99.9  99.9  34.0    Main CAF (0)
65.9  65.9     -      Data.Data.Lens fromOracle (35)
65.9  65.9     -        Data.Data.Lens hitTest (0)
65.9  65.9     -          Data.Data.Lens hitTest.\ (35)
65.9  65.9     -            Data.Data.Lens readCacheFollower (30)
65.9  65.9     -              Data.Data.Lens readCacheFollower.\ (30)
65.9  65.9     -                Data.Data.Lens insertHitMap (1)
65.9  65.9     -                  Data.Data.Lens insertHitMap.populate (1)
65.9  65.9  56.4                    Data.Data.Lens insertHitMap.populate.f (1824891)
 2.3   2.3   2.3                      Data.HashMap.Base clone16 (2682671)
 2.1   2.1   2.1                      Data.HashMap.Base hash (6204631)
 1.7   1.7    .4                      Data.HashMap.Array copy (1620382)
 1.3   1.3   1.3                        Data.HashMap.Array copy.\ (1620382)
 1.1   1.1   1.1                      Data.Data.Lens insertHitMap.populate.fs (2189870)
  .9    .9    .9                      Bound.Var gfoldl (364976)
  .5    .5    .5                      Data.HashMap.Array new_ (810191)
  .5    .5    .5                      Bound.Var gunfold (364976)
  .3    .3    .3                      Data.HashMap.Base sparseIndex (3620621)
  .2    .2    .2                      Bound.Scope gfoldl (182489)
```
---
Heap profile:

[![heap profile][2]][2]

  [2]: https://i.stack.imgur.com/RaI2L.png

**Comment by treeowl** [comment] 2017-06-14 04:23
The problem definitely has nothing to do with `Bound`. Here's a smaller reproduction:

```haskell
{-# LANGUAGE DeriveDataTypeable #-}

module Main (main) where
import           Control.Lens hiding (List)
import           Control.Lens.Plated
import           Data.Data (Data)
import           Data.Data.Lens (uniplate)
import Control.Exception
import Data.List (foldl')

data Expr a   = Var   a
              | List  [Expr a]
              | Apply (Expr a) (Expr a)
              | Lam   (Expr (Maybe a))
              | Nop
              deriving Data

-- Force the lists
forceList :: Expr a -> ()
forceList (List l) = foldl' (\() x -> forceList x) () l
forceList _ = ()

main = do
         evaluate $ forceList $ ex
         putStrLn "Hi!"
         evaluate $ forceList $ transform removeTest ex

ex :: Expr String
ex = List [ Apply (Var "test") $ List [Var "arg1", Var "arg2"]
          , Apply (Var "two") (Var "three")]

removeTest :: Expr String -> Expr String
removeTest = \expr -> case expr of
                        Apply (Var "test") _ -> Nop
                        _ -> expr

instance Data a => Plated (Expr a) where
  plate = uniplate
```

Notably, removing the `Lam` case makes the problem go away. The interesting thing about `Lam` is that it's the nested case, either directly (in my reduction) or indirectly (in the original). So that probably has something to do with it.

**Comment by treeowl** [comment] 2017-06-14 05:10
It looks like the frightening-looking caching mechanism is probably to blame. If I (presumably?) disable caching by defining

```haskell
readCacheFollower _ _ = Nothing
```

then the program seems to work.

**Comment by treeowl** [comment] 2017-06-14 05:22
@ThreeFx, I opened a ticket against `lens`, since the problem seems to be over there. Could you close this ticket please?

**Closed** 2017-06-14 09:19 UTC
